### ISSUE TITLE
Unknown Bug

### ISSUE THREAD

**Issue by Four-Study** [kimmo1019/Roundtrip#10]
Hi, I really like the idea of estimating density with neural networks and want to implement in my own research. When I tried the MNIST training example in a linux server, I encountered the following issue:
```
AbortedError (see above for traceback): Operation received an exception:Status: 5, message: could not create a view primitive descriptor, in file tensorflow/core/kernels/mkl_slice_op.cc:435
	 [[node gradients/g_net_1/concat_1_grad/Slice_1 (defined at main_density_est_img.py:103) ]]
```
Do you have any idea about the issue? Thank you in advance! 

System: Ubuntu 22.04.1 LTS
Python: 2.7
TensorFlow: 1.13.1

**Comment by codgas** [comment]
@Four-Study 
I created a docker image in which I was able to reproduce the MNIST Experiements with gpu
try:
```shell 
docker pull codgas/ubuntu18.04_cuda10.0_cudnn7_tf1.13.1_py2.7
```
for more informations check the fork on my profile

**Comment by kimmo1019** [comment]
> 



> @Four-Study I created a docker image in which I was able to reproduce the MNIST Experiements with gpu try:
> 
> ```shell
> docker pull codgas/ubuntu18.04_cuda10.0_cudnn7_tf1.13.1_py2.7
> ```
> 
> for more informations check the fork on my profile

Thanks! I already merged your pull request, I believe this should be really helpful! -Qiao

**Comment by Four-Study** [comment]
Thank you very much! I will have a try.
