### ISSUE TITLE
TypeError: __init__() takes at least 3 arguments (3 given) in "evaluate.py"

### ISSUE THREAD

**Issue by kannyjyk** [kimmo1019/Roundtrip#6]
When I want to visualize the estimated density on a 2D region, an error occurred:

> Traceback (most recent call last):
  File "evaluate.py", line 233, in <module>
    RTM = load_model(path,epoch,pretrain=args.pretrain)
  File "evaluate.py", line 197, in load_model
    xs = util.Gaussian_sampler(mean=np.zeros(x_dim),sd=1.0)
TypeError: __init__() takes at least 3 arguments (3 given)

And I add `N=20000` at the line 197 in "evaluate.py", like: 
```python
xs = util.Gaussian_sampler(N=20000,mean=np.zeros(x_dim),sd=1.0)
```
The code can run successfully.

**Comment by kimmo1019** [comment]
> When I want to visualize the estimated density on a 2D region, an error occurred:
> 
> > Traceback (most recent call last):
> > File "evaluate.py", line 233, in 
> > RTM = load_model(path,epoch,pretrain=args.pretrain)
> > File "evaluate.py", line 197, in load_model
> > xs = util.Gaussian_sampler(mean=np.zeros(x_dim),sd=1.0)
> > TypeError: **init**() takes at least 3 arguments (3 given)
> 
> And I add `N=20000` at the line 197 in "evaluate.py", like:
> 
> ```python
> xs = util.Gaussian_sampler(N=20000,mean=np.zeros(x_dim),sd=1.0)
> ```
> 
> The code can run successfully.

Thanks a lot for the feedback, I just found the version of the local rep is ahead of Github rep, so I made an update. Now the `N=20000` could be omitted.
