### ISSUE TITLE
Density estimation  for MNIST 

### ISSUE THREAD

**Issue by ankursing** [kimmo1019/Roundtrip#8]
I was trying to get the conditional density for MNIST dataset by running-
CUDA_VISIBLE_DEVICES=0 python main_density_est_img.py  --dx 100 --dy 784 --train True --data mnist --epochs 100 --cv_epoch 50 --patience 5;
training happens successfully  but not giving density at any directory . Could  you help me finding out a way to get the estimated conditional density.

**Comment by kimmo1019** [comment]
> I was trying to get the conditional density for MNIST dataset by running- CUDA_VISIBLE_DEVICES=0 python main_density_est_img.py --dx 100 --dy 784 --train True --data mnist --epochs 100 --cv_epoch 50 --patience 5; training happens successfully but not giving density at any directory . Could you help me finding out a way to get the estimated conditional density.

Sorry for the late reply. Email might be more efficient.
Is it due to the slow training? please make sure it was running using GPU.
