### ISSUE TITLE
Evaluation on simulated dataset (dimension > 2)

### ISSUE THREAD

**Issue by kiranchari** [kimmo1019/Roundtrip#9]
Hi,

I enjoyed reading your paper, kudos!

Could you please share details of the evaluation on the simulated independent GMM dataset (dimension > 2)? Was a random seed used when generating the dataset (for reproducibility)? What function was used to compute the Spearman correlation? 

It would also be great if you could share the raw data for Appendix Fig. S2. 

Thanks!

**Comment by kimmo1019** [comment]
Thanks for asking, in GMM simulator, `np.random.seed` was used for fixing random seed. 
Spearman correlation `scipy.stats.spearmanr` was used on test set.

The raw data was in a previous server, I'm trying to contact my previous lab member to see whether I can find it. Thanks!
